apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sqlflow-server
spec:
  selector:
    matchLabels:
      app: sqlflow-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlflow-server
    spec:
      containers:
      - image: sqlflow/sqlflow:server
        name: server
        imagePullPolicy: IfNotPresent
        command: ["sqlflowserver", "--argo-mode"]
        env:
        - name: SQLFLOW_WORKFLOW_LOGVIEW_ENDPOINT
          value: "http://localhost:9001"
        - name: SQLFLOW_WORKFLOW_STEP_IMAGE
          value: sqlflow/sqlflow:step
        - name: SQLFLOW_WORKFLOW_TTL
          value: "600"
        ports:
        - containerPort: 50051
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sqlflow-server
  labels:
    app: sqlflow-server
spec:
  ports:
  - port: 50051
    protocol: TCP
  selector:
    app: sqlflow-server
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sqlflow-jupyterhub
spec:
  selector:
    matchLabels:
      app: sqlflow-jupyterhub
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlflow-jupyterhub
    spec:
      containers:
      - image: sqlflow/sqlflow:jupyterhub
        name: jupyterhub
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /jupyter/certs
          name: cert-path
        env:
          - name: SQLFLOW_MYSQL_IMAGE
            value: sqlflow/sqlflow:mysql
          - name: SQLFLOW_JUPYTER_IMAGE
            value: sqlflow/sqlflow:jupyter
          - name: SQLFLOW_JUPYTER_SSL_KEY
            value: /jupyter/certs/playground.sqlflow.tech.key
          - name: SQLFLOW_JUPYTER_SSL_CERT
            value: /jupyter/certs/playground.sqlflow.tech.pem
          - name: SQLFLOW_JUPYTER_USE_GITHUB_OAUTH
            value: "true"
          - name: SQLFLOW_JUPYTER_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sqlflow
                key: jupyter_oauth_client_id
          - name: SQLFLOW_JUPYTER_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sqlflow
                key: jupyter_oauth_client_secret
        ports:
        - containerPort: 8000
          protocol: TCP
      volumes:
      - name: cert-path
        hostPath:
          path: /jupyter/certs
          type: DirectoryOrCreate
