apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sqlflow-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sqlflow-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlflow-server
    spec:
      containers:
      - image: sqlflow/sqlflow@sha256:863f135258fc2c824570a8e17c705bc70c5ce033499a9151e8cc0dca42df6df1
        name: sqlflow-server
        imagePullPolicy: Always
        command: ["sqlflowserver"]
        ports:
        - containerPort: 50051
          name: sqlflow-server

---

apiVersion: v1
kind: Service
metadata:
  name: sqlflow-server
  labels:
    app: sqlflow-server
spec:
  ports:
  - port: 50051
    protocol: TCP
  selector:
    app: sqlflow-server
