// Copyright 2019 The SQLFlow Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by goyacc -p sql -o parser.go sql.y. DO NOT EDIT.

//line sql.y:2
package sql

import __yyfmt__ "fmt"

//line sql.y:2

import (
	"fmt"
	"strings"
	"sync"
)

/* expr defines an expression as a Lisp list.  If len(val)>0,
   it is an atomic expression, in particular, NUMBER, IDENT,
   or STRING, defined by typ and val; otherwise, it is a
   Lisp S-expression. */
type expr struct {
	typ  int
	val  string
	sexp exprlist
}

type exprlist []*expr

/* construct an atomic expr */
func atomic(typ int, val string) *expr {
	return &expr{
		typ: typ,
		val: val,
	}
}

/* construct a funcall expr */
func funcall(name string, oprd exprlist) *expr {
	return &expr{
		sexp: append(exprlist{atomic(IDENT, name)}, oprd...),
	}
}

/* construct a unary expr */
func unary(typ int, op string, od1 *expr) *expr {
	return &expr{
		sexp: append(exprlist{atomic(typ, op)}, od1),
	}
}

/* construct a binary expr */
func binary(typ int, od1 *expr, op string, od2 *expr) *expr {
	return &expr{
		sexp: append(exprlist{atomic(typ, op)}, od1, od2),
	}
}

/* construct a variadic expr */
func variadic(typ int, op string, ods exprlist) *expr {
	return &expr{
		sexp: append(exprlist{atomic(typ, op)}, ods...),
	}
}

type extendedSelect struct {
	extended bool
	train    bool
	analyze  bool
	standardSelect
	trainClause
	predictClause
	analyzeClause
}

type standardSelect struct {
	fields exprlist
	tables []string
	where  *expr
	limit  string
}

type trainClause struct {
	estimator  string
	trainAttrs attrs
	columns    columnClause
	label      string
	save       string
}

/* If no FOR in the COLUMN, the key is "" */
type columnClause map[string]exprlist
type fieldClause exprlist

type attrs map[string]*expr

type predictClause struct {
	predAttrs attrs
	model     string
	into      string
}

type analyzeClause struct {
	analyzeAttrs attrs
	trainedModel string
	explainer    string
}

var parseResult *extendedSelect

func attrsUnion(as1, as2 attrs) attrs {
	for k, v := range as2 {
		if _, ok := as1[k]; ok {
			log.Panicf("attr %q already specified", as2)
		}
		as1[k] = v
	}
	return as1
}

//line sql.y:114
type sqlSymType struct {
	yys  int
	val  string /* NUMBER, IDENT, STRING, and keywords */
	flds exprlist
	tbls []string
	expr *expr
	expl exprlist
	atrs attrs
	eslt extendedSelect
	slct standardSelect
	tran trainClause
	colc columnClause
	labc string
	infr predictClause
	anal analyzeClause
}

const SELECT = 57346
const FROM = 57347
const WHERE = 57348
const LIMIT = 57349
const TRAIN = 57350
const PREDICT = 57351
const ANALYZE = 57352
const WITH = 57353
const COLUMN = 57354
const LABEL = 57355
const USING = 57356
const INTO = 57357
const FOR = 57358
const AS = 57359
const TO = 57360
const IDENT = 57361
const NUMBER = 57362
const STRING = 57363
const AND = 57364
const OR = 57365
const GE = 57366
const LE = 57367
const NE = 57368
const NOT = 57369
const POWER = 57370
const UMINUS = 57371

var sqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SELECT",
	"FROM",
	"WHERE",
	"LIMIT",
	"TRAIN",
	"PREDICT",
	"ANALYZE",
	"WITH",
	"COLUMN",
	"LABEL",
	"USING",
	"INTO",
	"FOR",
	"AS",
	"TO",
	"IDENT",
	"NUMBER",
	"STRING",
	"AND",
	"OR",
	"'>'",
	"'<'",
	"'='",
	"'!'",
	"GE",
	"LE",
	"NE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"NOT",
	"POWER",
	"UMINUS",
	"';'",
	"'('",
	"')'",
	"','",
	"'['",
	"']'",
	"'\"'",
	"'\\''",
}
var sqlStatenames = [...]string{}

const sqlEofCode = 1
const sqlErrCode = 2
const sqlInitialStackSize = 16

//line sql.y:329

/* Like Lisp's builtin function cdr. */
func (e *expr) cdr() (r []string) {
	for i := 1; i < len(e.sexp); i++ {
		r = append(r, e.sexp[i].String())
	}
	return r
}

/* Convert exprlist to string slice. */
func (el exprlist) Strings() (r []string) {
	for i := 0; i < len(el); i++ {
		r = append(r, el[i].String())
	}
	return r
}

func (e *expr) String() string {
	if e.typ == 0 { /* a compound expression */
		switch e.sexp[0].typ {
		case '+', '*', '/', '%', '=', '<', '>', '!', LE, GE, AND, OR:
			if len(e.sexp) != 3 {
				log.Panicf("Expecting binary expression, got %.10q", e.sexp)
			}
			return fmt.Sprintf("%s %s %s", e.sexp[1], e.sexp[0].val, e.sexp[2])
		case '-':
			switch len(e.sexp) {
			case 2:
				return fmt.Sprintf(" -%s", e.sexp[1])
			case 3:
				return fmt.Sprintf("%s - %s", e.sexp[1], e.sexp[2])
			default:
				log.Panicf("Expecting either unary or binary -, got %.10q", e.sexp)
			}
		case '(':
			if len(e.sexp) != 2 {
				log.Panicf("Expecting ( ) as unary operator, got %.10q", e.sexp)
			}
			return fmt.Sprintf("(%s)", e.sexp[1])
		case '[':
			return "[" + strings.Join(e.cdr(), ", ") + "]"
		case NOT:
			return fmt.Sprintf("NOT %s", e.sexp[1])
		case IDENT: /* function call */
			return e.sexp[0].val + "(" + strings.Join(e.cdr(), ", ") + ")"
		}
	} else {
		return fmt.Sprintf("%s", e.val)
	}

	log.Panicf("Cannot print an unknown expression")
	return ""
}

func (s standardSelect) String() string {
	r := "SELECT "
	if len(s.fields) == 0 {
		r += "*"
	} else {
		for i := 0; i < len(s.fields); i++ {
			r += s.fields[i].String()
			if i != len(s.fields)-1 {
				r += ", "
			}
		}
	}
	r += "\nFROM " + strings.Join(s.tables, ", ")
	if s.where != nil {
		r += fmt.Sprintf("\nWHERE %s", s.where)
	}
	if len(s.limit) > 0 {
		r += fmt.Sprintf("\nLIMIT %s", s.limit)
	}
	return r
}

// sqlReentrantParser makes sqlParser, generated by goyacc and using a
// global variable parseResult to return the result, reentrant.
type sqlSyncParser struct {
	pr sqlParser
}

func newParser() *sqlSyncParser {
	return &sqlSyncParser{sqlNewParser()}
}

var mu sync.Mutex

func (p *sqlSyncParser) Parse(s string) (r *extendedSelect, e error) {
	defer func() {
		if r := recover(); r != nil {
			var ok bool
			e, ok = r.(error)
			if !ok {
				e = fmt.Errorf("%v", r)
			}
		}
	}()

	mu.Lock()
	defer mu.Unlock()

	p.pr.Parse(newLexer(s))
	return parseResult, nil
}

//line yacctab:1
var sqlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const sqlPrivate = 57344

const sqlLast = 203

var sqlAct = [...]int{

	46, 129, 128, 87, 12, 38, 54, 40, 39, 41,
	37, 113, 53, 63, 112, 114, 141, 138, 117, 91,
	48, 116, 96, 63, 47, 25, 89, 26, 43, 34,
	18, 49, 82, 44, 45, 40, 39, 41, 62, 63,
	90, 17, 139, 139, 57, 61, 88, 88, 48, 77,
	16, 88, 47, 80, 81, 88, 43, 36, 60, 49,
	83, 44, 45, 84, 79, 86, 95, 78, 124, 97,
	98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
	108, 109, 110, 144, 40, 39, 41, 142, 50, 9,
	140, 10, 131, 14, 59, 119, 122, 48, 120, 8,
	121, 47, 66, 67, 68, 43, 130, 15, 49, 24,
	44, 45, 136, 134, 133, 123, 55, 132, 94, 125,
	4, 64, 65, 66, 67, 68, 85, 56, 132, 35,
	137, 33, 28, 27, 22, 21, 127, 89, 135, 126,
	132, 143, 75, 76, 71, 70, 69, 118, 73, 72,
	74, 64, 65, 66, 67, 68, 75, 76, 71, 70,
	69, 111, 73, 72, 74, 64, 65, 66, 67, 68,
	71, 70, 69, 29, 73, 72, 74, 64, 65, 66,
	67, 68, 52, 31, 93, 51, 30, 19, 20, 23,
	3, 11, 42, 58, 32, 13, 7, 6, 115, 5,
	92, 2, 1,
}
var sqlPact = [...]int{

	186, -1000, 81, 74, -1000, 11, 2, -9, 179, 116,
	115, 184, 92, -17, -13, -1000, -1000, -1000, -1000, 114,
	113, 162, 172, 112, -11, 110, 16, 77, 171, 97,
	108, 97, 52, -1000, 65, -1000, -1000, -3, 134, -1000,
	-13, -1000, -1000, 65, 46, 43, -1000, 65, 65, -12,
	97, 107, 97, 13, -1000, 14, -1000, 5, 177, 99,
	65, -19, -1000, 65, 65, 65, 65, 65, 65, 65,
	65, 65, 65, 65, 65, 65, 65, 120, -31, -35,
	-1000, -1000, -1000, -29, 9, -1000, 4, 132, 97, 79,
	65, 96, -1000, 48, -1000, 134, -1000, 134, 69, 69,
	-1000, -1000, -1000, 90, 90, 90, 90, 90, 90, 146,
	146, -1000, -1000, -1000, -1000, 124, 73, 95, 94, -1000,
	-1000, -1000, 134, -1000, -1000, 123, 93, 73, 1, -1000,
	-1000, -13, -1000, -1000, -1000, 71, -1000, 0, 68, 73,
	-1000, 64, -1000, -1000, -1000,
}
var sqlPgo = [...]int{

	0, 202, 201, 200, 199, 198, 3, 197, 196, 195,
	194, 5, 0, 1, 193, 10, 192, 2, 191, 6,
	12,
}
var sqlR1 = [...]int{

	0, 1, 1, 1, 1, 2, 14, 14, 3, 3,
	4, 4, 4, 7, 7, 8, 8, 5, 5, 5,
	18, 18, 9, 9, 9, 13, 13, 13, 17, 17,
	6, 6, 10, 10, 19, 20, 20, 12, 12, 15,
	15, 16, 16, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11,
}
var sqlR2 = [...]int{

	0, 2, 3, 3, 3, 6, 0, 2, 0, 2,
	9, 8, 7, 5, 7, 4, 6, 2, 4, 5,
	5, 1, 1, 1, 3, 1, 1, 1, 1, 3,
	2, 2, 1, 3, 3, 1, 3, 3, 4, 1,
	3, 2, 3, 1, 1, 1, 1, 3, 3, 3,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 2, 2,
}
var sqlChk = [...]int{

	-1000, -1, -2, 4, 39, -4, -7, -8, 18, 8,
	10, -18, -12, -9, 19, 33, 39, 39, 39, 8,
	9, 19, 19, 5, 17, 42, 40, 19, 19, 11,
	14, 11, -10, 19, 40, 19, 41, -15, -11, 20,
	19, 21, -16, 40, 45, 46, -12, 36, 32, 43,
	11, 14, 11, -20, -19, 19, 19, -20, -14, 42,
	6, -15, 41, 42, 31, 32, 33, 34, 35, 26,
	25, 24, 29, 28, 30, 22, 23, -11, 21, 21,
	-11, -11, 44, -15, -20, 19, -20, -6, 42, 13,
	26, 14, -3, 7, 19, -11, 41, -11, -11, -11,
	-11, -11, -11, -11, -11, -11, -11, -11, -11, -11,
	-11, 41, 45, 46, 44, -5, 12, 14, 15, -19,
	19, 21, -11, 19, 20, -6, 15, 12, -17, -13,
	33, 19, -12, 19, 19, 15, 19, -17, 16, 42,
	19, 16, 19, -13, 19,
}
var sqlDef = [...]int{

	0, -2, 0, 0, 1, 0, 0, 0, 0, 0,
	0, 0, 0, 21, 23, 22, 2, 3, 4, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 6, 32, 0, 24, 37, 0, 39, 43,
	44, 45, 46, 0, 0, 0, 50, 0, 0, 0,
	0, 0, 0, 0, 35, 0, 15, 0, 8, 0,
	0, 0, 38, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	64, 65, 41, 0, 0, 13, 0, 0, 0, 0,
	0, 0, 5, 0, 33, 7, 20, 40, 51, 52,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 47, 48, 49, 42, 0, 0, 0, 0, 36,
	30, 31, 34, 16, 9, 0, 0, 0, 17, 28,
	25, 26, 27, 14, 12, 0, 11, 0, 0, 0,
	10, 0, 18, 29, 19,
}
var sqlTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 27, 45, 3, 3, 35, 3, 46,
	40, 41, 33, 31, 42, 32, 3, 34, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 39,
	25, 26, 24, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 43, 3, 44,
}
var sqlTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 28, 29, 30, 36, 37, 38,
}
var sqlTok3 = [...]int{
	0,
}

var sqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	sqlDebug        = 0
	sqlErrorVerbose = false
)

type sqlLexer interface {
	Lex(lval *sqlSymType) int
	Error(s string)
}

type sqlParser interface {
	Parse(sqlLexer) int
	Lookahead() int
}

type sqlParserImpl struct {
	lval  sqlSymType
	stack [sqlInitialStackSize]sqlSymType
	char  int
}

func (p *sqlParserImpl) Lookahead() int {
	return p.char
}

func sqlNewParser() sqlParser {
	return &sqlParserImpl{}
}

const sqlFlag = -1000

func sqlTokname(c int) string {
	if c >= 1 && c-1 < len(sqlToknames) {
		if sqlToknames[c-1] != "" {
			return sqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func sqlStatname(s int) string {
	if s >= 0 && s < len(sqlStatenames) {
		if sqlStatenames[s] != "" {
			return sqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func sqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !sqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range sqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + sqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := sqlPact[state]
	for tok := TOKSTART; tok-1 < len(sqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < sqlLast && sqlChk[sqlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if sqlDef[state] == -2 {
		i := 0
		for sqlExca[i] != -1 || sqlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; sqlExca[i] >= 0; i += 2 {
			tok := sqlExca[i]
			if tok < TOKSTART || sqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if sqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += sqlTokname(tok)
	}
	return res
}

func sqllex1(lex sqlLexer, lval *sqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = sqlTok1[0]
		goto out
	}
	if char < len(sqlTok1) {
		token = sqlTok1[char]
		goto out
	}
	if char >= sqlPrivate {
		if char < sqlPrivate+len(sqlTok2) {
			token = sqlTok2[char-sqlPrivate]
			goto out
		}
	}
	for i := 0; i < len(sqlTok3); i += 2 {
		token = sqlTok3[i+0]
		if token == char {
			token = sqlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = sqlTok2[1] /* unknown char */
	}
	if sqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", sqlTokname(token), uint(char))
	}
	return char, token
}

func sqlParse(sqllex sqlLexer) int {
	return sqlNewParser().Parse(sqllex)
}

func (sqlrcvr *sqlParserImpl) Parse(sqllex sqlLexer) int {
	var sqln int
	var sqlVAL sqlSymType
	var sqlDollar []sqlSymType
	_ = sqlDollar // silence set and not used
	sqlS := sqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	sqlstate := 0
	sqlrcvr.char = -1
	sqltoken := -1 // sqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		sqlstate = -1
		sqlrcvr.char = -1
		sqltoken = -1
	}()
	sqlp := -1
	goto sqlstack

ret0:
	return 0

ret1:
	return 1

sqlstack:
	/* put a state and value onto the stack */
	if sqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", sqlTokname(sqltoken), sqlStatname(sqlstate))
	}

	sqlp++
	if sqlp >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlS[sqlp] = sqlVAL
	sqlS[sqlp].yys = sqlstate

sqlnewstate:
	sqln = sqlPact[sqlstate]
	if sqln <= sqlFlag {
		goto sqldefault /* simple state */
	}
	if sqlrcvr.char < 0 {
		sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
	}
	sqln += sqltoken
	if sqln < 0 || sqln >= sqlLast {
		goto sqldefault
	}
	sqln = sqlAct[sqln]
	if sqlChk[sqln] == sqltoken { /* valid shift */
		sqlrcvr.char = -1
		sqltoken = -1
		sqlVAL = sqlrcvr.lval
		sqlstate = sqln
		if Errflag > 0 {
			Errflag--
		}
		goto sqlstack
	}

sqldefault:
	/* default state action */
	sqln = sqlDef[sqlstate]
	if sqln == -2 {
		if sqlrcvr.char < 0 {
			sqlrcvr.char, sqltoken = sqllex1(sqllex, &sqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if sqlExca[xi+0] == -1 && sqlExca[xi+1] == sqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			sqln = sqlExca[xi+0]
			if sqln < 0 || sqln == sqltoken {
				break
			}
		}
		sqln = sqlExca[xi+1]
		if sqln < 0 {
			goto ret0
		}
	}
	if sqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			sqllex.Error(sqlErrorMessage(sqlstate, sqltoken))
			Nerrs++
			if sqlDebug >= 1 {
				__yyfmt__.Printf("%s", sqlStatname(sqlstate))
				__yyfmt__.Printf(" saw %s\n", sqlTokname(sqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for sqlp >= 0 {
				sqln = sqlPact[sqlS[sqlp].yys] + sqlErrCode
				if sqln >= 0 && sqln < sqlLast {
					sqlstate = sqlAct[sqln] /* simulate a shift of "error" */
					if sqlChk[sqlstate] == sqlErrCode {
						goto sqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if sqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", sqlS[sqlp].yys)
				}
				sqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if sqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", sqlTokname(sqltoken))
			}
			if sqltoken == sqlEofCode {
				goto ret1
			}
			sqlrcvr.char = -1
			sqltoken = -1
			goto sqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production sqln */
	if sqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", sqln, sqlStatname(sqlstate))
	}

	sqlnt := sqln
	sqlpt := sqlp
	_ = sqlpt // guard against "declared and not used"

	sqlp -= sqlR2[sqln]
	// sqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if sqlp+1 >= len(sqlS) {
		nyys := make([]sqlSymType, len(sqlS)*2)
		copy(nyys, sqlS)
		sqlS = nyys
	}
	sqlVAL = sqlS[sqlp+1]

	/* consult goto table to find next state */
	sqln = sqlR1[sqln]
	sqlg := sqlPgo[sqln]
	sqlj := sqlg + sqlS[sqlp].yys + 1

	if sqlj >= sqlLast {
		sqlstate = sqlAct[sqlg]
	} else {
		sqlstate = sqlAct[sqlj]
		if sqlChk[sqlstate] != -sqln {
			sqlstate = sqlAct[sqlg]
		}
	}
	// dummy call; replaced with literal code
	switch sqlnt {

	case 1:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:159
		{
			parseResult = &extendedSelect{
				extended:       false,
				standardSelect: sqlDollar[1].slct}
		}
	case 2:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:164
		{
			parseResult = &extendedSelect{
				extended:       true,
				train:          true,
				standardSelect: sqlDollar[1].slct,
				trainClause:    sqlDollar[2].tran}
		}
	case 3:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:171
		{
			parseResult = &extendedSelect{
				extended:       true,
				train:          false,
				standardSelect: sqlDollar[1].slct,
				predictClause:  sqlDollar[2].infr}
		}
	case 4:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:178
		{
			parseResult = &extendedSelect{
				extended:       true,
				train:          false,
				analyze:        true,
				standardSelect: sqlDollar[1].slct,
				analyzeClause:  sqlDollar[2].anal}
		}
	case 5:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:189
		{
			sqlVAL.slct.fields = sqlDollar[2].expl
			sqlVAL.slct.tables = sqlDollar[4].tbls
			sqlVAL.slct.where = sqlDollar[5].expr
			sqlVAL.slct.limit = sqlDollar[6].val
		}
	case 6:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:198
		{
		}
	case 7:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:199
		{
			sqlVAL.expr = sqlDollar[2].expr
		}
	case 8:
		sqlDollar = sqlS[sqlpt-0 : sqlpt+1]
//line sql.y:203
		{
		}
	case 9:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:204
		{
			sqlVAL.val = sqlDollar[2].val
		}
	case 10:
		sqlDollar = sqlS[sqlpt-9 : sqlpt+1]
//line sql.y:208
		{
			sqlVAL.tran.estimator = sqlDollar[3].val
			sqlVAL.tran.trainAttrs = sqlDollar[5].atrs
			sqlVAL.tran.columns = sqlDollar[6].colc
			sqlVAL.tran.label = sqlDollar[7].labc
			sqlVAL.tran.save = sqlDollar[9].val
		}
	case 11:
		sqlDollar = sqlS[sqlpt-8 : sqlpt+1]
//line sql.y:215
		{
			sqlVAL.tran.estimator = sqlDollar[3].val
			sqlVAL.tran.trainAttrs = sqlDollar[5].atrs
			sqlVAL.tran.columns = sqlDollar[6].colc
			sqlVAL.tran.save = sqlDollar[8].val
		}
	case 12:
		sqlDollar = sqlS[sqlpt-7 : sqlpt+1]
//line sql.y:221
		{
			sqlVAL.tran.estimator = sqlDollar[2].val
			sqlVAL.tran.trainAttrs = sqlDollar[4].atrs
			sqlVAL.tran.label = sqlDollar[5].labc
			sqlVAL.tran.save = sqlDollar[7].val
		}
	case 13:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:230
		{
			sqlVAL.infr.into = sqlDollar[3].val
			sqlVAL.infr.model = sqlDollar[5].val
		}
	case 14:
		sqlDollar = sqlS[sqlpt-7 : sqlpt+1]
//line sql.y:231
		{
			sqlVAL.infr.into = sqlDollar[3].val
			sqlVAL.infr.predAttrs = sqlDollar[5].atrs
			sqlVAL.infr.model = sqlDollar[7].val
		}
	case 15:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:235
		{
			sqlVAL.anal.trainedModel = sqlDollar[2].val
			sqlVAL.anal.explainer = sqlDollar[4].val
		}
	case 16:
		sqlDollar = sqlS[sqlpt-6 : sqlpt+1]
//line sql.y:236
		{
			sqlVAL.anal.trainedModel = sqlDollar[2].val
			sqlVAL.anal.analyzeAttrs = sqlDollar[4].atrs
			sqlVAL.anal.explainer = sqlDollar[6].val
		}
	case 17:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:240
		{
			sqlVAL.colc = map[string]exprlist{"feature_columns": sqlDollar[2].expl}
		}
	case 18:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:241
		{
			sqlVAL.colc = map[string]exprlist{sqlDollar[4].val: sqlDollar[2].expl}
		}
	case 19:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:242
		{
			sqlVAL.colc[sqlDollar[5].val] = sqlDollar[3].expl
		}
	case 20:
		sqlDollar = sqlS[sqlpt-5 : sqlpt+1]
//line sql.y:246
		{
			sqlVAL.expl = exprlist{sqlDollar[1].expr, atomic(IDENT, "AS"), funcall("", sqlDollar[4].expl)}
		}
	case 21:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:249
		{
			sqlVAL.expl = sqlDollar[1].flds
		}
	case 22:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:253
		{
			sqlVAL.flds = append(sqlVAL.flds, atomic(IDENT, "*"))
		}
	case 23:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:254
		{
			sqlVAL.flds = append(sqlVAL.flds, atomic(IDENT, sqlDollar[1].val))
		}
	case 24:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:255
		{
			sqlVAL.flds = append(sqlDollar[1].flds, atomic(IDENT, sqlDollar[3].val))
		}
	case 25:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:259
		{
			sqlVAL.expr = atomic(IDENT, "*")
		}
	case 26:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:260
		{
			sqlVAL.expr = atomic(IDENT, sqlDollar[1].val)
		}
	case 27:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:261
		{
			sqlVAL.expr = sqlDollar[1].expr
		}
	case 28:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:265
		{
			sqlVAL.expl = exprlist{sqlDollar[1].expr}
		}
	case 29:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:266
		{
			sqlVAL.expl = append(sqlDollar[1].expl, sqlDollar[3].expr)
		}
	case 30:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:270
		{
			sqlVAL.labc = sqlDollar[2].val
		}
	case 31:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:271
		{
			sqlVAL.labc = sqlDollar[2].val[1 : len(sqlDollar[2].val)-1]
		}
	case 32:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:275
		{
			sqlVAL.tbls = []string{sqlDollar[1].val}
		}
	case 33:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:276
		{
			sqlVAL.tbls = append(sqlDollar[1].tbls, sqlDollar[3].val)
		}
	case 34:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:280
		{
			sqlVAL.atrs = attrs{sqlDollar[1].val: sqlDollar[3].expr}
		}
	case 35:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:284
		{
			sqlVAL.atrs = sqlDollar[1].atrs
		}
	case 36:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:285
		{
			sqlVAL.atrs = attrsUnion(sqlDollar[1].atrs, sqlDollar[3].atrs)
		}
	case 37:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:289
		{
			sqlVAL.expr = funcall(sqlDollar[1].val, nil)
		}
	case 38:
		sqlDollar = sqlS[sqlpt-4 : sqlpt+1]
//line sql.y:290
		{
			sqlVAL.expr = funcall(sqlDollar[1].val, sqlDollar[3].expl)
		}
	case 39:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:294
		{
			sqlVAL.expl = exprlist{sqlDollar[1].expr}
		}
	case 40:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:295
		{
			sqlVAL.expl = append(sqlDollar[1].expl, sqlDollar[3].expr)
		}
	case 41:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:299
		{
			sqlVAL.expl = nil
		}
	case 42:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:300
		{
			sqlVAL.expl = sqlDollar[2].expl
		}
	case 43:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:304
		{
			sqlVAL.expr = atomic(NUMBER, sqlDollar[1].val)
		}
	case 44:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:305
		{
			sqlVAL.expr = atomic(IDENT, sqlDollar[1].val)
		}
	case 45:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:306
		{
			sqlVAL.expr = atomic(STRING, sqlDollar[1].val)
		}
	case 46:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:307
		{
			sqlVAL.expr = variadic('[', "square", sqlDollar[1].expl)
		}
	case 47:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:308
		{
			sqlVAL.expr = unary('(', "paren", sqlDollar[2].expr)
		}
	case 48:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:309
		{
			sqlVAL.expr = unary('"', "quota", atomic(STRING, sqlDollar[2].val))
		}
	case 49:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:310
		{
			sqlVAL.expr = unary('\'', "quota", atomic(STRING, sqlDollar[2].val))
		}
	case 50:
		sqlDollar = sqlS[sqlpt-1 : sqlpt+1]
//line sql.y:311
		{
			sqlVAL.expr = sqlDollar[1].expr
		}
	case 51:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:312
		{
			sqlVAL.expr = binary('+', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 52:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:313
		{
			sqlVAL.expr = binary('-', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 53:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:314
		{
			sqlVAL.expr = binary('*', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 54:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:315
		{
			sqlVAL.expr = binary('/', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 55:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:316
		{
			sqlVAL.expr = binary('%', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 56:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:317
		{
			sqlVAL.expr = binary('=', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 57:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:318
		{
			sqlVAL.expr = binary('<', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 58:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:319
		{
			sqlVAL.expr = binary('>', sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 59:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:320
		{
			sqlVAL.expr = binary(LE, sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 60:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:321
		{
			sqlVAL.expr = binary(GE, sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 61:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:322
		{
			sqlVAL.expr = binary(NE, sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 62:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:323
		{
			sqlVAL.expr = binary(AND, sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 63:
		sqlDollar = sqlS[sqlpt-3 : sqlpt+1]
//line sql.y:324
		{
			sqlVAL.expr = binary(OR, sqlDollar[1].expr, sqlDollar[2].val, sqlDollar[3].expr)
		}
	case 64:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:325
		{
			sqlVAL.expr = unary(NOT, sqlDollar[1].val, sqlDollar[2].expr)
		}
	case 65:
		sqlDollar = sqlS[sqlpt-2 : sqlpt+1]
//line sql.y:326
		{
			sqlVAL.expr = unary('-', sqlDollar[1].val, sqlDollar[2].expr)
		}
	}
	goto sqlstack /* stack new state and value */
}
