#!/bin/bash
set -e
. /miniconda/etc/profile.d/conda.sh
source activate sqlflow-dev

go generate ./...
go get -v -t ./...
go install ./...
SQLFLOW_TEST_DB=hive SQLFLOW_log_level=debug go test -v ./...
